# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_code', models.IntegerField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('factory_id', models.CharField(max_length=100)),
                ('parameters', models.TextField()),
                ('manufactor', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('acquisition_date', models.DateField()),
                ('received_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('keeper', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('demo', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hqk.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contactor', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=254)),
                ('attachments', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('evaluation', models.CharField(max_length=100)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hqk.Supplier'),
        ),
        migrations.AddField(
            model_name='category',
            name='suppliers',
            field=models.ManyToManyField(to='hqk.Supplier'),
        ),
    ]
