# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hqk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=100)),
                ('production_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('value', models.FloatField()),
                ('manufactor', models.CharField(max_length=100)),
                ('demo', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('receipe_date', models.DateField()),
                ('receipe_number', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=100)),
                ('buyer', models.CharField(max_length=100)),
                ('repository', models.CharField(max_length=100)),
                ('department', models.CharField(default='hqk', max_length=100)),
                ('quanlity', models.IntegerField()),
                ('summary', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hqk.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=100)),
                ('production_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('value', models.FloatField()),
                ('manufactor', models.CharField(max_length=100)),
                ('demo', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('receipe_date', models.DateField()),
                ('receipe_number', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('usage', models.CharField(max_length=100)),
                ('quanlity', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hqk.Category')),
                ('materialIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hqk.MaterialIn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='applicant',
            field=models.CharField(default='hanbin', max_length=100),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='charger',
            field=models.CharField(default='scsh', max_length=100),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='chief',
            field=models.CharField(default='moufs', max_length=100),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='department',
            field=models.CharField(default='hqk', max_length=100),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='director',
            field=models.CharField(default='yhl', max_length=100),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='reson',
            field=models.TextField(default='for a test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='title',
            field=models.CharField(default='application for materials', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='attachments',
            field=models.FileField(upload_to='./uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='materialin',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hqk.Supplier'),
        ),
    ]
