# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hqk', '0002_auto_20170120_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AlterModelOptions(
            name='materialin',
            options={'verbose_name': '入库单', 'verbose_name_plural': '入库单'},
        ),
        migrations.AlterModelOptions(
            name='materialout',
            options={'verbose_name': '出库单', 'verbose_name_plural': '出库单'},
        ),
        migrations.AlterModelOptions(
            name='materialrequisition',
            options={'verbose_name': '申请单', 'verbose_name_plural': '申请单'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '设备供应商', 'verbose_name_plural': '设备供应商'},
        ),
        migrations.AddField(
            model_name='device',
            name='bid',
            field=models.CharField(default='自主采购', max_length=100, verbose_name='设备来源'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.IntegerField(verbose_name='类别代码'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, verbose_name='种类名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='summary',
            field=models.TextField(verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='device',
            name='acquisition_date',
            field=models.DateField(verbose_name='购置日期'),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hqk.Category', verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='device',
            name='demo',
            field=models.TextField(verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='device',
            name='department',
            field=models.CharField(max_length=100, verbose_name='使用科室'),
        ),
        migrations.AlterField(
            model_name='device',
            name='factory_id',
            field=models.CharField(max_length=100, verbose_name='出厂编号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='keeper',
            field=models.CharField(max_length=100, verbose_name='保管人'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufactor',
            field=models.CharField(max_length=100, verbose_name='生产厂家'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=100, verbose_name='规格型号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='device',
            name='number',
            field=models.CharField(max_length=100, verbose_name='唯一性编号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='parameters',
            field=models.TextField(verbose_name='参数'),
        ),
        migrations.AlterField(
            model_name='device',
            name='received_date',
            field=models.DateField(verbose_name='启用日期'),
        ),
        migrations.AlterField(
            model_name='device',
            name='release_date',
            field=models.DateField(verbose_name='出厂日期'),
        ),
        migrations.AlterField(
            model_name='device',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hqk.Supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='device',
            name='value',
            field=models.FloatField(verbose_name='价值'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='buyer',
            field=models.CharField(max_length=100, verbose_name='采购人'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hqk.Category', verbose_name='物资种类'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='demo',
            field=models.TextField(verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='department',
            field=models.CharField(default='后勤科', max_length=100, verbose_name='接收部门'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='expired_date',
            field=models.DateField(verbose_name='到期日期'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='lot',
            field=models.CharField(max_length=100, verbose_name='批号'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='maker',
            field=models.CharField(max_length=100, verbose_name='出单人'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='manufactor',
            field=models.CharField(max_length=100, verbose_name='生产厂家'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='model',
            field=models.CharField(max_length=100, verbose_name='规格型号'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='name',
            field=models.CharField(max_length=100, verbose_name='物资名称'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='production_date',
            field=models.DateField(verbose_name='生产日期'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='quanlity',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='receipe_date',
            field=models.DateField(verbose_name='单据日期'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='receipe_number',
            field=models.CharField(max_length=100, verbose_name='单据编号'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='repository',
            field=models.CharField(max_length=100, verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='summary',
            field=models.CharField(max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hqk.Supplier', verbose_name='供货商'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='type',
            field=models.CharField(max_length=100, verbose_name='业务类别'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='unit',
            field=models.CharField(max_length=100, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='materialin',
            name='value',
            field=models.FloatField(verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hqk.Category', verbose_name='物资种类'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='demo',
            field=models.TextField(verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='department',
            field=models.CharField(max_length=100, verbose_name='领用科室'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='expired_date',
            field=models.DateField(verbose_name='到期日期'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='lot',
            field=models.CharField(max_length=100, verbose_name='批号'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='maker',
            field=models.CharField(max_length=100, verbose_name='出单人'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='manufactor',
            field=models.CharField(max_length=100, verbose_name='生产厂家'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='materialIn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hqk.MaterialIn', verbose_name='对应入库单'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='model',
            field=models.CharField(max_length=100, verbose_name='规格型号'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='name',
            field=models.CharField(max_length=100, verbose_name='物资名称'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='production_date',
            field=models.DateField(verbose_name='生产日期'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='quanlity',
            field=models.CharField(max_length=100, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='receipe_date',
            field=models.DateField(verbose_name='单据日期'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='receipe_number',
            field=models.CharField(max_length=100, verbose_name='单据编号'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='type',
            field=models.CharField(max_length=100, verbose_name='业务类别'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='unit',
            field=models.CharField(max_length=100, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='usage',
            field=models.CharField(max_length=100, verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='user',
            field=models.CharField(max_length=100, verbose_name='领用人'),
        ),
        migrations.AlterField(
            model_name='materialout',
            name='value',
            field=models.FloatField(verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='applicant',
            field=models.CharField(default='hanbin', max_length=100, verbose_name='申请者'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='charger',
            field=models.CharField(default='scsh', max_length=100, verbose_name='分管领导'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='chief',
            field=models.CharField(default='moufs', max_length=100, verbose_name='科长'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='department',
            field=models.CharField(default='后勤科', max_length=100, verbose_name='科室'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='director',
            field=models.CharField(default='yhl', max_length=100, verbose_name='主管领导'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='reson',
            field=models.TextField(verbose_name='原因'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=254, verbose_name='公司地址：'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='attachments',
            field=models.FileField(upload_to='./uploads/%Y/%m/%d/', verbose_name='三证附件：'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='公司名称：'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_phone',
            field=models.CharField(max_length=100, verbose_name='公司电话：'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contactor',
            field=models.CharField(max_length=100, verbose_name='联系人：'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='电子邮箱：'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='evaluation',
            field=models.CharField(max_length=100, verbose_name='评价等级：'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='手机：'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='summary',
            field=models.TextField(verbose_name='公司经营范围：'),
        ),
    ]
